### ISSUE TITLE
Not working on Vue 3 with Vite

### ISSUE THREAD

**Issue by itsrafsanjani** [haiafara/vue-it-bigger#393]
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.t2 (LightBox.vue:3:20)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5649:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at instance.update (runtime-core.esm-bundler.js:5763:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5777:9)
    at mountComponent (runtime-core.esm-bundler.js:5559:9)
    at processComponent (runtime-core.esm-bundler.js:5517:17)
    at patch (runtime-core.esm-bundler.js:5119:21)
    at mountChildren (runtime-core.esm-bundler.js:5303:13)
```

**Comment by janosrusiczki** [comment]
Hello, sorry for the late reply. I specifically updated the description of the npm to specify that it's for Vue 2. I will be integrating it with Vue 3 in the foreseeable future, so there might be a new version but I'm not making any promises.

**Comment by eakenbor** [comment]
@janosrusiczki any plans for Vue 3 soon?

**Comment by janosrusiczki** [comment]
Many years later, but with [version 1.0.0](https://github.com/haiafara/vue-it-bigger/releases/tag/v1.0.0) the library was switched to Vite / Vue 3.
