### ISSUE TITLE
Error with Nuxt 2

### ISSUE THREAD

**Issue by thunderBestPower** [haiafara/vue-it-bigger#417]
Hi, 

I have a problem.

if I add your library and use the command "yarn generate" or "yarn build" or "yarn dev" the execute this fails giving me the following error:

ERROR in ./.nuxt/client.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: this.getOptions is not a function
    at Object.loader (/home/mattia/PhpstormProjects/xxx/node_modules/babel-loader/lib/index.js:44:28)
    at Object.<anonymous> (/home/mattia/PhpstormProjects/xxx/node_modules/babel-loader/lib/index.js:39:12)
 @ multi ./.nuxt/client.js app[0]

My package.json is:

"dependencies": {
    "@nuxtjs/axios": "^5.3.6",
    "@nuxtjs/i18n": "^7.3.1",
    "cross-env": "^5.2.0",
    "js-file-download": "^0.4.7",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "nuxt": "^2.4.0",
    "nuxt-validate": "^1.0.1",
    "postcss": "^8.4.27",
    "postcss-import": "^15.1.0",
    "standard-version": "^7.0.0",
    "ts-node": "^8.3.0",
    "vue-it-bigger": "^0.3.2",
    "vue-signature": "^2.6.0",
    "vuedraggable": "^2.24.3",
    "vuex-pathify": "^1.2.4"
  },
  "devDependencies": {
    "@nuxt/types": "~2.14.0",
    "@nuxt/typescript": "^2.8.1",
    "@nuxtjs/dotenv": "^1.4.1",
    "@nuxtjs/eslint-config": "^0.0.1",
    "@nuxtjs/vuetify": "^1.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^7.14.1",
    "eslint-config-prettier": "^4.1.0",
    "eslint-config-standard": ">=12.0.0",
    "eslint-loader": "^2.1.2",
    "eslint-plugin-import": "^2.28.0",
    "eslint-plugin-jest": ">=22.3.0",
    "eslint-plugin-n": "^16.0.1",
    "eslint-plugin-node": ">=8.0.1",
    "eslint-plugin-nuxt": ">=0.4.2",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-promise": ">=4.0.1",
    "eslint-plugin-standard": ">=4.0.0",
    "eslint-plugin-vue": "^7.1.0",
    "node-sass": "^9.0.0",
    "nodemon": "^1.18.9",
    "prettier": "^1.16.4",
    "sass-loader": "^10.1.1",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2"
  }
  
Ccould you help me?
Best regards

**Comment by janosrusiczki** [comment]
Hello, I have recently released v1.0.0 and 1.1.0. I have removed the Nuxt references from the readme (aka I'm not offering support because I'm not a Nuxt user), but since the project was upgraded to Vue 3 and Vite there might be a chance that it works now.
